=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/extensions/authorAction.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
    targetNamespace="http://www.oxygenxml.com/ns/author/external-action"
    xmlns:ea="http://www.oxygenxml.com/ns/author/external-action">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/XML/1998/namespace"/>

    <xs:element name="authorAction">
        <xs:annotation>
            <xs:documentation>An author action definition.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element ref="ea:name"/>
                <xs:element ref="ea:description" minOccurs="0"/>
                <xs:element ref="ea:smallIconPath" minOccurs="0"/>
                <xs:element ref="ea:largeIconPath" minOccurs="0"/>
                <xs:element ref="ea:accessKey" minOccurs="0"/>
                <xs:element ref="ea:accelerator" minOccurs="0"/>
                <xs:element ref="ea:enabledInReadOnlyContext" minOccurs="0"/>
                <xs:element ref="ea:operations"/>
            </xs:all>
            <xs:attribute name="id" type="ea:idType" use="required">
                <xs:annotation>
                    <xs:documentation>The action's ID. It is used to refer this action from a toolbar or menu.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:assertion test="string-length($value) > 0"
                    xmlns:xerces="http://xerces.apache.org"
                    xerces:message="The 'name' element cannot be empty."/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="description" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                A description of the action. It usually appears on the tooltip.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="largeIconPath" type="ea:imageType">
        <xs:annotation>
            <xs:documentation>
                <p>The path to an icon that will be used when the action is added to a toolbar.
                It is recommended to use <code>${framework}</code> or <code>${frameworkDir}</code> to refer images from within the framework directory.</p>
                <p>If the path starts with a slash ('/'), the resource will be searched for in the Classpath of the framework.</p>
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="smallIconPath" type="ea:imageType">
        <xs:annotation>
            <xs:documentation>
                The path to an icon that will be used when the action is added on the toolbar.
                It is recommended to use <code>${framework}</code> or <code>${frameworkDir}</code> to refer images from within the framework directory.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="accessKey" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                <p>In Windows, you can access menus by holding down the <code>Alt</code> key and then pressing the key that corresponds to the letter that is underlined 
                in the name of the menu. Then, while still holding down <code>Alt,</code> you can select submenus and menu action the same way, by pressing the subsequent 
                    corresponding keys.</p> 
                <p>You can use this element to specify the letter in the name of the action that can be used to access the action.</p>
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="accelerator" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                <p>This element allows you to configure a shortcut for the action that you are editing. The + character separates the shortcut keys.</p>
                <p>The "M" modifier keys are a platform-independent way of representing keys:
                    <ul>
                        <li>M1 is the COMMAND key on MacOS X, and the CTRL key on other platforms.</li>
                        <li>M2 is the SHIFT key.</li>
                        <li>M3 is the Option key on MacOS X, and the ALT key on other platforms.</li>
                        <li>M4 is the CTRL key on MacOS X, and is undefined on other platforms.</li>
                    </ul>
                </p>
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="enabledInReadOnlyContext" type="xs:boolean" default="false">
        <xs:annotation>
            <xs:documentation>
                If <code>true,</code> the action can be invoked even when the cursor is placed in a read-only location.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:element name="operations">
        <xs:annotation>
            <xs:documentation>
                <p>Element used to configure the functionality of the action that you are editing.</p>
                <p>An action has one or more operation modes. The evaluation of an XPath 2.0 expression activates an operation mode.
                    The first selected operation mode is activated when you trigger the action.</p>
                <p>The scope of the XPath expression must consist only of element and attribute nodes of the edited document.
                    Otherwise, the XPath expression does not return a match and does not fire the action. </p>
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="ea:operation"/>
            </xs:sequence>
            <xs:attribute ref="xml:base" fixed="preserve"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="operation">
        <xs:complexType>
            <xs:all>
                <xs:element name="xpathCondition" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>An XPath 2.0 expression used for operation activation.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:space" fixed="preserve">
                                    <xs:annotation>
                                        <xs:documentation>If the content is a simple text then we can control how it is treated.</xs:documentation>
                                    </xs:annotation>
                                </xs:attribute>
                                <xs:attribute ref="xml:base"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="arguments" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>The arguments for the invoked operation.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="ea:argument" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="id" use="required" type="ea:idType">
                <xs:annotation>
                    <xs:documentation>The qualified name of the operation class: <i>ro.sync.ecss.extensions.commons.operations.InsertFragmentOperation</i>. A built-in operation can be specified just by its name: <i>InsertFragmentOperation</i>.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="xml:base" fixed="preserve"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="argument">
        <xs:annotation>
            <xs:documentation>An argument or parameter for an author operation.</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0">
                <xs:any namespace="##local" processContents="skip" maxOccurs="unbounded"/>
                <xs:any namespace="##other" processContents="skip" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute name="name" use="required"/>
            <xs:attribute ref="xml:space" fixed="preserve">
                <xs:annotation>
                    <xs:documentation>If the content is a simple text then we can control how it is treated.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute ref="xml:base" fixed="preserve"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="imageType">
        <xs:attribute name="href">
            <xs:annotation>
                <xs:documentation>
                    <p>The path to an icon. It is recommended to use <code>${framework}</code> or <code>${frameworkDir}</code> to refer images from within the framework directory.</p>
                    <p>If the path starts with a slash ('/'), the resource will be searched for in the Classpath of the framework.</p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:assertion test="string-length($value) > 0" xmlns:xerces="http://xerces.apache.org"
                xerces:message="The 'id' attribute cannot be empty."/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/dita-lw_externalAuthorActions/paragraph.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="paragraph">
  <a:name>${i18n(paragraph)}</a:name>
  <a:description>${i18n(paragraph_description)}</a:description>
  <a:smallIconPath href="/images/Paragraph16.png"/>
  <a:largeIconPath href="/images/Paragraph24.png"/>
  <a:operations>
    <a:operation id="InsertFragmentOperation">
      <a:xpathCondition>parent::body</a:xpathCondition>
      <a:arguments>
        <a:argument name="fragment"><p/></a:argument>
        <a:argument name="insertLocation">.</a:argument>
        <a:argument name="insertPosition">After</a:argument>
      </a:arguments>
    </a:operation>
    <a:operation id="InsertFragmentOperation">
      <a:xpathCondition>oxy:allows-child-element("*", "class", " topic/p ")</a:xpathCondition>
      <a:arguments>
        <a:argument name="fragment"><p/></a:argument>
        <a:argument name="insertPosition">After</a:argument>
      </a:arguments>
    </a:operation>
    <a:operation id="InsertFragmentOperation">
      <a:xpathCondition>ancestor-or-self::p</a:xpathCondition>
      <a:arguments>
        <a:argument name="fragment"><p/></a:argument>
        <a:argument name="insertLocation">ancestor-or-self::p[1]</a:argument>
        <a:argument name="insertPosition">After</a:argument>
      </a:arguments>
    </a:operation>
    <a:operation id="SurroundWithFragmentOperation">
      <a:arguments>
        <a:argument name="fragment"><p/></a:argument>
      </a:arguments>
    </a:operation>
  </a:operations>
  <a:accelerator>M1 M2 P</a:accelerator>
  <a:accessKey>P</a:accessKey>
  <a:enabledInReadOnlyContext>false</a:enabledInReadOnlyContext>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/dita-lw_externalAuthorActions/insert.cross.reference2.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="insert.cross.reference2">
  <a:name>${i18n(insert.cross.reference)}</a:name>
  <a:description>${i18n(insert.cross.reference_description)}</a:description>
  <a:smallIconPath href="/images/Link16.png"/>
  <a:largeIconPath href="/images/Link24.png"/>
  <a:operations>
    <a:operation id="InsertFragmentOperation">
      <a:xpathCondition>oxy:allows-child-element("*", "class", " topic/xref ")</a:xpathCondition>
      <a:arguments>
        <a:argument name="fragment"><xref>${caret}</xref></a:argument>
      </a:arguments>
    </a:operation>
  </a:operations>
  <a:enabledInReadOnlyContext>false</a:enabledInReadOnlyContext>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/dita-lw_externalAuthorActions/insert.table.column.after.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="insert.table.column.after">
  <a:name>${i18n(insert.table.column.after)}</a:name>
  <a:description>${i18n(insert.table.column.after_description)}</a:description>
  <a:smallIconPath href="/images/TableColumn16.png"/>
  <a:largeIconPath href="/images/TableColumn24.png"/>
  <a:operations>
    <a:operation id="ro.sync.ecss.extensions.dita.topic.table.cals.InsertSingleColumnOperation">
      <a:xpathCondition>ancestor-or-self::node()[self::*[contains(@class," topic/row ") or contains(@class," topic/strow ") or contains(@class," topic/sthead ")]][1][self::*[contains(@class," topic/row ")]]</a:xpathCondition>
      <a:arguments>
        <a:argument name="defaultNamespace"/>
        <a:argument name="insertLocation">After</a:argument>
      </a:arguments>
    </a:operation>
    <a:operation
      id="ro.sync.ecss.extensions.dita.topic.table.simpletable.InsertSingleColumnOperation">
      <a:xpathCondition>ancestor-or-self::simpletable</a:xpathCondition>
      <a:arguments/>
    </a:operation>
  </a:operations>
  <a:enabledInReadOnlyContext>false</a:enabledInReadOnlyContext>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/externalAuthorActions/insert.topicref.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="insert.topicref">
  <a:name>${i18n(insert.topicref2)}</a:name>
  <a:description>${i18n(insert.topicref_description2)}</a:description>
  <a:largeIconPath href="/images/Topicref24.png"/>
  <a:smallIconPath href="/images/Topicref16.png"/>
  <a:accessKey>R</a:accessKey>
  <a:operations>
    <a:operation id="ro.sync.ecss.extensions.dita.map.topicref.InsertTopicrefOperation">
      <a:xpathCondition>self::*[contains(@class, " map/map ") or contains(@class, " map/topicref ") or contains(@class, " map/relcell ") or contains(@class, " map/relcolspec ")]</a:xpathCondition>
    </a:operation>
  </a:operations>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/dita-lw_externalAuthorActions/x.fig.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="x.fig">
  <a:name>${i18n(fig)}</a:name>
  <a:description>${i18n(fig_description)}</a:description>
  <a:operations>
    <a:operation id="ExecuteMultipleWebappCompatibleActionsOperation">
      <a:arguments>
        <a:argument name="actionIDs">done.editing
fig
</a:argument>
      </a:arguments>
    </a:operation>
  </a:operations>
  <a:accessKey>F</a:accessKey>
  <a:enabledInReadOnlyContext>false</a:enabledInReadOnlyContext>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/dita-lw_externalAuthorActions/x.pre.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="x.pre">
  <a:name>${i18n(pre)}</a:name>
  <a:description>${i18n(pre_description)}</a:description>
  <a:operations>
    <a:operation id="ExecuteMultipleWebappCompatibleActionsOperation">
      <a:arguments>
        <a:argument name="actionIDs">done.editing
pre
</a:argument>
      </a:arguments>
    </a:operation>
  </a:operations>
  <a:accessKey>P</a:accessKey>
  <a:enabledInReadOnlyContext>false</a:enabledInReadOnlyContext>
</a:authorAction>

=== AgoraIO/agora_doc_source/scripts/oxygen/frameworks/dita/externalAuthorActions/insert.new.topic.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:authorAction xmlns:a="http://www.oxygenxml.com/ns/author/external-action"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oxygenxml.com/ns/author/external-action http://www.oxygenxml.com/ns/author/external-action/authorAction.xsd"
  id="insert.new.dita.resource">
  <a:name>${i18n(insert.new.dita.resource)}</a:name>
  <a:description>${i18n(insert.new.dita.resource_description)}</a:description>
  <a:largeIconPath href="/images/NewTopic24.png"/>
  <a:smallIconPath href="/images/NewTopic16.png"/>
  <a:accessKey>N</a:accessKey>
  <a:operations>
    <a:operation id="ro.sync.ecss.extensions.dita.map.topicref.InsertNewTopicOperation">
      <a:xpathCondition>self::*[contains(@class, " map/map ") or contains(@class, " map/topicref ") or contains(@class, " map/relcell ") or contains(@class, " map/relcolspec ")]</a:xpathCondition>
    </a:operation>
  </a:operations>
</a:authorAction>
