=== AgoraIO/agora_doc_source/scripts/oxygen/lib/third-party-components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="third-party">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="component"/>
            </xs:sequence>
            <xs:attribute name="base-dir" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="component">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element maxOccurs="unbounded" ref="file-path" minOccurs="0"/>
                <xs:element name="version" type="xs:string"/>
                <xs:element ref="project-info"/>
                <xs:element ref="license"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="product" use="required">
                <xs:simpleType>
                    <xs:list>
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="editor"/>
                                <xs:enumeration value="author"/>
                                <xs:enumeration value="author-comp"/>
                                <xs:enumeration value="author-sdk"/>
                                <xs:enumeration value="developer"/>
                                <xs:enumeration value="webhelp"/>
                                <xs:enumeration value="diff"/>
                                <xs:enumeration value="svn"/>
                                <xs:enumeration value="webapp"/>
                                <xs:enumeration value="chemistry"/>
                                <xs:enumeration value="publishing-engine"/>                                
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:list>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="file-path">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute default="false" name="isDir" type="xs:boolean"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="project-info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="about" type="xs:string"/>
                <xs:element maxOccurs="unbounded" name="licensor" nillable="false" type="xs:string"/>
                <xs:element name="start-year">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="project-url" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="license">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" type="xs:string"/>
                <xs:choice>
                    <xs:element name="path" type="xs:string"/>
                    <xs:element name="content" type="xs:string"/>
                </xs:choice>
                <xs:element name="url" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AgoraIO/agora_doc_source/scripts/oxygen/lib/third-party-components.xml
<?xml version="1.0" encoding="UTF-8"?>
<third-party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="third-party-components.xsd" base-dir="lib">
	<component id="antlr" product="editor author developer">
		<name>ANTLR</name>
		<file-path>antlr.jar</file-path>
		<version>2.7.5</version>
		<!-- Used by ANTLR si SVN Kit. -->
		<project-info>
			<about>A framework for constructing recognizers, compilers, and translators from grammatical descriptions containing Java, C#, C++, or Python actions.</about>
			<licensor>Terence Parr and Sam Harwell</licensor>
			<start-year>1989</start-year>
			<project-url>http://www.antlr.org</project-url>
		</project-info>
		<license>
			<type>The BSD License</type>
			<path>antlr-runtime.LICENSE.txt</path>
			<url>http://www.antlr.org/license.html</url>
		</license>
	</component>
	<component id="antlr-runtime" product="editor author developer">
		<name>ANTLR Runtime</name>
		<file-path>antlr-runtime-3.4.jar</file-path>
		<version>3.4</version>
		<!-- Used by ANTLR si SVN Kit. ANTLR3 include the runtime -->
		<project-info>
			<about>A framework for constructing recognizers, compilers, and translators from grammatical descriptions containing Java, C#, C++, or Python actions.</about>
			<licensor>Terence Parr and Sam Harwell</licensor>
			<start-year>1989</start-year>
			<project-url>http://www.antlr.org</project-url>
		</project-info>
		<license>
			<type>The BSD License</type>
			<path>antlr-runtime.LICENSE.txt</path>
			<url>http://www.antlr.org/license.html</url>
		</license>
	</component>
 	<component id="batik-svg-toolkit"
		product="editor author developer author-comp author-sdk chemistry">
		<name>Batik SVG Toolkit</name>
		<file-path>oxygen-patched-batik.jar</file-path>
		<version>1.14</version>
		<project-info>
			<about>Batik is a Java-based toolkit for applications or applets that want to use images in the 
                Scalable Vector Graphics (SVG) format for various purposes, such as display, generation or manipulation. The library was modified by Syncro Soft SRL to allow a closer integration in oXygen and to fix other issues.</about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>2000</start-year>
			<project-url>http://xmlgraphics.apache.org/batik/index.html</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>oxygen-patched-batik.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
	<component id="apache-commons-httpclient4.0" product="editor author developer diff svn">
		<!-- http://archive.apache.org/dist/httpcomponents/commons-httpclient/source/ -->
		<name>Apache HttpClient</name>
		<file-path>fluent-hc-4.5.9.jar</file-path>
		<file-path>httpclient-4.5.9.jar</file-path>
		<file-path>httpclient-cache-4.5.9.jar</file-path>
		<file-path>httpcore-4.4.11.jar</file-path>
		<file-path>httpmime-4.5.9.jar</file-path>
		<file-path>httpclient-win-4.5.9.jar</file-path>
		<version>4.5.1</version>
		<project-info>
			<about>Provides an efficient, up-to-date, and feature-rich package implementing the client side of the most recent HTTP standards and recommendations.</about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>2009</start-year>
			<project-url>http://hc.apache.org/httpcomponents-client-ga/index.html</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>httpclient-4.3.5.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
	<component id="apache-commons-io" product="editor author developer">
		<name>Apache Commons IO</name>
        <file-path>commons-io-2.8.0.jar</file-path>
		<version>2.8.0</version>
		<project-info>
			<about>Commons IO is a library of utilities to assist with developing IO functionality.</about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>2002</start-year>
			<project-url>http://commons.apache.org/io/</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>commons-io.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
	<component id="apache-commons-logging" product="editor author developer diff svn">
		<name>Apache Commons Logging</name>
		<file-path>commons-logging-1.2.jar</file-path>
		<version>1.2</version>
		<project-info>
			<about>Commons-logging comes with support for a number of popular logging implementations, and writing adapters for others is a reasonably simple task.</about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>2001</start-year>
			<project-url>http://commons.apache.org/logging/</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>commons-logging.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
	<component id="w3c-css-validator" product="editor author developer">
		<name>Oxygen W3C CSS Validator</name>
		<file-path>oxygen-patched-css-validator.jar</file-path>
		<version>1.0.4</version>
		<project-info>
			<about>Software created by the W3C to help Web designers and Web developers check Cascading Style Sheets (CSS). 
               Is the most used and most reliable CSS validator available. The library was modified by Syncro Soft SRL to allow a closer integration in oXygen.</about>
			<licensor>W3C, Syncro Soft SRL</licensor>
			<start-year>2002</start-year>
			<project-url>http://jigsaw.w3.org/css-validator/</project-url>
		</project-info>
		<license>
			<type>W3C Software Notice and License</type>
			<path>oxygen-patched-css-validator.LICENSE.txt</path>
			<url>http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231</url>
		</license>
	</component>
	<component id="flute" product="editor author developer">
		<name>W3C Flute</name>
		<file-path>oxygen-css-flute-parser.jar</file-path>
		<version>1.3</version>
		<project-info>
			<about>Flute is a parser that implements the standard interface for CSS parser (https://www.w3.org/Style/CSS/SAC/)
            	and supposed to work with CSS1, CSS2, CSS3 (currently under development) and 
            	other CSS derived languages. The current implementation from oXygen has been enhanced 
            	to support part of the CSS Level 3 standard. The source code is available at: 
            	https://www.oxygenxml.com/external_resources.html </about>
			<licensor>W3C (Massachusetts Institute of Technology, Institut National de Recherche en Informatique et en Automatique, Keio University)</licensor>
			<start-year>2002</start-year>
			<project-url>https://www.w3.org/Style/CSS/SAC/</project-url>
		</project-info>
		<license>
			<type>W3C Software Notice and License</type>
			<path>flute.LICENSE.txt</path>
			<url>https://www.w3.org/Consortium/Legal/copyright-software-19980720</url>
		</license>
	</component>

	<component id="apache-fop" product="editor author developer chemistry">
		<name>Apache FOP</name>
        <file-path>oxygen-patched-fop.jar</file-path>
		<version>2.6</version>
		<project-info>
			<about>Apache FOP (Formatting Objects Processor) is a print formatter driven by XSL formatting objects (XSL-FO) 
                and an output independent formatter. It is a Java application that reads a formatting object (FO) tree and 
                renders the resulting pages to a specified output. Output formats currently supported include PDF, PS, PCL,
                AFP, XML (area tree representation), Print, AWT and PNG, and to a lesser extent, RTF and TXT. The primary output target is PDF. 
                The library was modified by Syncro Soft SRL to allow a closer integration in oXygen and to fix other issues.</about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>1999</start-year>
			<project-url>http://xmlgraphics.apache.org/fop/</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>oxygen-patched-fop.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
  
  <component id="fop-pdf-images" product="chemistry">
    <name>Apache FOP PDF Images Plug-In</name>
    <file-path>fop-pdf-images-2.6.jar</file-path>
    <version>2.6</version>
    <project-info>
      <about>The fop-pdf-images plug-in extends FOP in order to add support for using PDF images in fo:external-graphic elements when generating PDF files.</about>
      <licensor>Apache Software Foundation</licensor>
      <start-year>2012</start-year>
      <project-url>https://xmlgraphics.apache.org/fop/fop-pdf-images.html</project-url>
    </project-info>
    <license>
      <type>Apache License 2.0</type>
      <path>fop-pdf-images.LICENSE.txt</path>
      <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
    </license>
  </component>
  
	<component id="font-box" product="editor author developer chemistry">
		<name>Apache FontBox</name>
		<file-path>fontbox-2.0.19.jar</file-path>
		<version>2.0.19</version>
		<project-info>
			<about>The Apache FontBox library is an open source Java tool to obtain low level information from font files. FontBox is a sub
                project of Apache PDFBox. </about>
			<licensor>Apache Software Foundation</licensor>
			<start-year>2006</start-year>
			<project-url>http://pdfbox.apache.org/</project-url>
		</project-info>
		<license>
			<type>Apache License 2.0</type>
			<path>fontbox.LICENSE.txt</path>
			<url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
		</license>
	</component>
 
  <component id="pdf-box" product="editor author developer chemistry">
      <name>Apache PDFBox - A Java PDF Library</name>
      <file-path>pdfbox-2.0.19.jar</file-path>
      <version>2.0.19</version>
